import type { DepartmentRunView } from "../interface.js";

export const scriptedDepartmentRun: DepartmentRunView = {
  run: {
    id: "run-1",
    projectId: "project-1",
    departmentId: "department-1",
    pipelineVersionId: "pipeline-1",
    snapshotRevisionId: "snapshot-1",
    parentRunId: null,
    forkedFromSnapshotRevisionId: null,
    status: "ready",
    revision: 0,
    createdAt: "2026-07-15T00:00:00.000Z",
    updatedAt: "2026-07-15T00:00:00.000Z",
  },
  snapshot: {
    id: "snapshot-1",
    revision: 1,
    parentRevision: null,
    hash: "a".repeat(64),
    canonicalJson: "{}",
    payload: {
      schemaVersion: 1,
      project: {
        id: "project-1",
        revision: 0,
        name: "Checkout",
        goal: "Ship it",
        sharedContext: "",
        repositoryReferences: [],
      },
      department: {
        id: "department-1",
        revision: 1,
        name: "Delivery",
        description: "",
        inputArtifactContracts: [],
        outputArtifactContracts: [],
        defaultExecutionProfileId: "profile-1",
      },
      pipelineVersion: {
        id: "pipeline-1",
        version: 1,
        hash: "b".repeat(64),
        graph: {
          nodes: [
            { id: "start", type: "start", name: "Start" },
            { id: "complete", type: "complete", name: "Complete" },
          ],
          edges: [{ from: "start", to: "complete" }],
        },
      },
      skillFlows: [],
      positions: [],
      executionProfiles: [
        {
          id: "profile-1",
          revision: 0,
          name: "Scripted",
          providerRef: "scripted",
          model: "scripted-v1",
          sandboxRef: "no-sandbox",
          branchStrategy: "head",
          limits: {
            timeoutSeconds: 60,
            maxIterations: 1,
            maxTokens: null,
          },
          retryPolicy: { maxAttempts: 0 },
          permissionPolicy: "deny",
          secretReferenceIds: [],
        },
      ],
      runLimits: { maxActiveNodes: 1 },
    },
  },
  nodes: [
    {
      id: "node-run-start",
      runId: "run-1",
      pipelineNodeId: "start",
      nodeType: "start",
      status: "ready",
      attemptCount: 0,
      attempts: [],
      approvals: [],
      requiredDependencyIds: [],
      result: null,
      failure: null,
      createdAt: "2026-07-15T00:00:00.000Z",
      updatedAt: "2026-07-15T00:00:00.000Z",
    },
    {
      id: "node-run-complete",
      runId: "run-1",
      pipelineNodeId: "complete",
      nodeType: "complete",
      status: "queued",
      attemptCount: 0,
      attempts: [],
      approvals: [],
      requiredDependencyIds: ["start"],
      result: null,
      failure: null,
      createdAt: "2026-07-15T00:00:00.000Z",
      updatedAt: "2026-07-15T00:00:00.000Z",
    },
  ],
};
